---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
#  - name: debian-6.0
#    driver:
#      box: puppetlabs/debian-6.0.10-64-nocm
#      box_url: https://atlas.hashicorp.com/puppetlabs/boxes/debian-6.0.10-64-nocm/versions/1.0.2/providers/virtualbox.box
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: debian-8.2
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[backuppc::default]
  - name: server
    run_list:
      - recipe[backuppc::server]
